framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  session:
    handler_id: null
    cookie_secure: auto
    cookie_path: /

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
